### ISSUE TITLE
AWS Region should be configurable via AWS_REGION environment variable

### ISSUE THREAD

**Issue by ankon** [Collaborne/nodemailer-ses-sender#2]
https://github.com/Collaborne/nodemailer-ses-sender/blob/6a468904bf588447e072e4354e68ae95da6a50b1/index.js#L11

The AWS SDK doesn't pick up the `AWS_REGION` environment variable by default, so usually you want to be explicit:
```js
const ses = new AWS.SES({..., region: process.env.AWS_REGION });
```

**Comment by cminardi** [comment]
Simply setting the environment variable has worked for me so far (hence the [documentation](https://github.com/Collaborne/nodemailer-ses-sender/blob/master/README.md#usage)). 
Is it better to provide it explicitly?

**Comment by ankon** [comment]
Missed to reply here: if the sdk now picks up the setting automatically, then that's fine. It used to not do that, i.e. 'AWS_REGION' wasn't a documented variable it worked with. It seems this is now the case, so we can stop defaulting/requiring it: http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html states
> You can set the region using the AWS_REGION environment variable. If you define this variable, the SDK for JavaScript reads it and uses it.
